campaign/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

app_name = 'game'

router = DefaultRouter()
router.register(r'user', views.UserViewSet)
router.register(r'pilot', views.PilotViewSet)

urlpatterns = [
    path('pilot/<int:pk>', views.PilotUpdate.as_view(), name='pilot'),
    path('rulebook/<int:pk>', views.RulebookView.as_view(), name='rulebook'),

    path('campaign/<int:pk>', views.CampaignView.as_view(), name='campaign'),
    #path('campaign/<int:pk>/plan', views.CampaignUpdate.as_view(), name='campaign-plan'),

    path('campaign/<int:pk>/plan', views.SessionPlan.as_view(), name='next-mission'),

    path('session/<int:session_id>', views.session_summary, name='session'),
    path('session/<int:pk>/debrief', views.SessionDebrief.as_view(), name='session-debrief'),

    path('profile/', views.player_page, name='player_profile'),
    path('player/<int:player_id>', views.player_page, name="player_update"),

    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

campaign/models/ai.py
from django.db import models
from django.utils.functional import cached_property

from .campaigns import Rulebook
from xwtools.models import Dial, DialManeuver, ArcDirectionChoice, RangeChoice


class AI(models.Model):
    rulebook = models.ForeignKey(Rulebook, on_delete=models.CASCADE)
    dial = models.ForeignKey(Dial, on_delete=models.CASCADE)
    flee = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return '{} AI'.format(self.dial.chassis.name)


    def mirror(self):
        """
        A helper function that makes left-sided copies of all the right-side maneuver tables
        :return: Nothing, saves new objects directly
        """
        right_arcs = (ArcDirectionChoice.FR, ArcDirectionChoice.RF, ArcDirectionChoice.RA, ArcDirectionChoice.AR)

        for mv in self.aimaneuver_set.filter(arc__in=right_arcs):
            new_arc = mv.arc.replace('R', 'L')
            if not self.aimaneuver_set.filter(arc=new_arc, range=mv.range).exists():
                mv.pk = None
                mv.arc = new_arc
                mv.roll_1 = mv.roll_1.find_mirror()
                mv.roll_2 = mv.roll_2.find_mirror()
                mv.roll_3 = mv.roll_3.find_mirror()
                mv.roll_4 = mv.roll_4.find_mirror()
                mv.roll_5 = mv.roll_5.find_mirror()
                mv.roll_6 = mv.roll_6.find_mirror()
                mv.save()

    class Meta:
        verbose_name_plural = 'AI'

    @cached_property
    def has_special(self):
        return self.aimaneuver_set.filter(arc=ArcDirectionChoice.SP).exists()


class AIManeuver(models.Model):
    ai = models.ForeignKey(AI, on_delete=models.CASCADE)
    arc = models.CharField(max_length=2, choices=ArcDirectionChoice.choices)
    range = models.CharField(max_length=1, choices=RangeChoice.choices)

    # these are denormalized mainly to make data entry easier, so we don't need
    # to have an AI, AIManeuver, and a theoretical AIManeuverRoll model all on one admin page
    roll_1 = models.ForeignKey(DialManeuver, on_delete=models.CASCADE, related_name='roll_1')
    roll_2 = models.ForeignKey(DialManeuver, on_delete=models.CASCADE, related_name='roll_2')
    roll_3 = models.ForeignKey(DialManeuver, on_delete=models.CASCADE, related_name='roll_3')
    roll_4 = models.ForeignKey(DialManeuver, on_delete=models.CASCADE, related_name='roll_4')
    roll_5 = models.ForeignKey(DialManeuver, on_delete=models.CASCADE, related_name='roll_5')
    roll_6 = models.ForeignKey(DialManeuver, on_delete=models.CASCADE, related_name='roll_6')

    class Meta:
        ordering = ['arc', 'range']

    def get_maneuvers(self): return True

    @cached_property
    def rolls(self):
        return [self.roll_1, self.roll_2, self.roll_3, self.roll_4, self.roll_5, self.roll_6]

    @cached_property
    def arc_order(self):
        return ['FL', 'BE', 'FR', 'LF', 'RF', 'LA', 'RA', 'AL', 'AR'].index(self.arc)


class AIPriority(models.Model):
    TYPE_CHOICES = (
        ('U', 'System Phase'),
        ('T', 'Target'),
        ('A', 'Action')
    )
    ai = models.ForeignKey(AI, on_delete=models.CASCADE, related_name='priorities')
    type = models.CharField(max_length=1, choices=TYPE_CHOICES)
    step = models.PositiveSmallIntegerField(default=1)
    desc = models.CharField(max_length=75)

    class Meta:
        verbose_name_plural = 'AI Priorities'
        ordering = ['-type', 'step']

campaign/models/campaigns.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.utils.functional import cached_property

from math import floor

from xwtools.models import Chassis, Faction, SlotChoice, Card
from .enemies import EnemyPilot


class User(AbstractUser):
    pass


class UpgradeLogic(models.IntegerChoices):
    HOTAC = 1, 'HotAC'
    TEST = 2, 'Test'


class FeatureChoice(models.TextChoices):
    EMPLACEMENT = 'E', 'Emplacement'
    OBSTACLE = 'O', 'Obstacle'
    TERRAIN = 'T', 'Terrain'


class Rulebook(models.Model):
    description = models.CharField(max_length=30)
    admin = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    faction = models.ForeignKey(Faction, on_delete=models.SET_NULL, null=True)
    ships = models.ManyToManyField(Chassis, through='PlayableShip')

    # player defaults
    start_init = models.PositiveSmallIntegerField(default=2)

    # configure a campaign's XP costs
    ship_cost = models.PositiveSmallIntegerField(default=5)

    upgrade_logic = models.PositiveSmallIntegerField(choices=UpgradeLogic.choices)
    initiative_progression = models.PositiveSmallIntegerField(choices=UpgradeLogic.choices)
    initiative_cost = models.PositiveSmallIntegerField(default=3)

    starter_mission = models.ForeignKey('Mission', on_delete=models.SET_NULL, null=True, related_name='starts')

    def __str__(self):
        return self.description

    def get_absolute_url(self):
        return reverse('ruleset', kwargs={'pk': self.pk})

    def get_initiative_cost(self, initiative):
        """
        Returns the XP cost of advancing to from 'iniative'-1 to 'initiative'.
        """
        if self.initiative_progression == UpgradeLogic.TEST:
            return (initiative*self.initiative_cost)^2
        elif self.initiative_progression == UpgradeLogic.HOTAC:
            return initiative * self.initiative_cost
        else:
            return 0


class PlayableShip(models.Model):
    rulebook = models.ForeignKey(Rulebook, on_delete=models.CASCADE)
    chassis = models.ForeignKey(Chassis, on_delete=models.CASCADE)
    xp_value = models.SmallIntegerField(default = 0)

    PROGRESSION_TYPES = (
        ('d', 'Default'),
        ('h', 'HWK-290')
    )
    progression = models.CharField(max_length=1, choices=PROGRESSION_TYPES, default='d')

    @cached_property
    def name(self):
        return self.chassis.name

    def __str__(self):
        return self.name


class MissionFeature(models.Model):
    name = models.CharField(max_length=30)
    type = models.CharField(max_length=1, choices=FeatureChoice.choices)
    setup_code = models.CharField(max_length=1, blank=True)
    attack = models.PositiveSmallIntegerField(null=True, blank=True)
    attack_range = models.CharField(max_length=3, blank=True)
    hull = models.PositiveSmallIntegerField(null=True, blank=True)
    shields = models.PositiveSmallIntegerField(null=True, blank=True)
    agility = models.PositiveSmallIntegerField(null=True, blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    @cached_property
    def is_emplacement(self):
        return self.type == FeatureChoice.EMPLACEMENT

class Mission(models.Model):
    FRIENDLY = 'F'
    NEUTRAL = 'N'
    HOSTILE = 'H'
    TERRITORY_CHOICES = (
        (FRIENDLY, 'Friendly'),
        (NEUTRAL, 'Neutral'),
        (HOSTILE, 'Hostile')
    )
    name = models.CharField(max_length=30)
    story = models.CharField(max_length=30)
    sequence = models.PositiveSmallIntegerField()
    enemy_faction = models.ForeignKey(Faction, on_delete=models.CASCADE, default=1)
    territory = models.CharField(max_length=1, choices=TERRITORY_CHOICES, default=NEUTRAL)
    rulebook = models.ForeignKey(Rulebook, on_delete=models.SET_NULL, null=True)
    turns = models.PositiveSmallIntegerField(default=12)

    player_vp = models.BooleanField(default=False)
    enemy_vp =  models.BooleanField(default=False)

    objective = models.TextField()
    bonus_1 = models.TextField(blank=True, null=True)
    bonus_2 = models.TextField(blank=True, null=True)
    penalty = models.TextField(blank=True, null=True)

    ground_assault = models.BooleanField(default=False)

    features = models.ManyToManyField(MissionFeature, blank=True)

    class Meta:
        ordering = ['story', 'sequence']
        indexes = [
            models.Index(fields=['story', 'sequence']),
            models.Index(fields=['rulebook']),
            models.Index(fields=['player_vp'])
        ]

    def __str__(self):
        return '{} ({} {})'.format(self.name, self.story, self.sequence)


class Campaign(models.Model):
    rulebook = models.ForeignKey(Rulebook, on_delete=models.SET_NULL, null=True)
    gm = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='campaign_gm')
    players = models.ManyToManyField(User)
    description = models.CharField(max_length=30)

    victory = models.PositiveSmallIntegerField(default=12)
    pool_xp = models.BooleanField(default=False)

    deck = models.ManyToManyField(Mission)
    deck_draw = models.JSONField(null=True)

    exclude_random = models.ManyToManyField(Chassis, blank=True)

    def __str__(self):
        return self.description

    @property
    def victory_points(self):
        return self.session_set.filter(outcome='V', player_vp=True).Count()

    @cached_property
    def xp_share(self):
        """
        Used when XP pooling is chosen for the game.
        Calculates total xp across all sessions and total number of pilot shares.
        Each mission flown earns a pilot one share in the group's total xp.
        """
        pilots = 0
        xp = 0
        for s in self.session_set.all():
            pilots = pilots + s.pilots.count()
            xp = xp + s.xp_total
        return floor(xp/pilots)

    @cached_property
    def limited_upgrades(self):
        from .pilots import PilotUpgrade
        return PilotUpgrade.objects.filter(pilot__campaign=self, card__limited=True).values_list('card__name', flat=True)

    def starting_deck(self):
        for m in Mission.objects.filter(rulebook=self.rulebook, sequence=1):
            self.deck.add(m)
        self.save()

    def draw_missions(self):
        from random import sample
        deck = list(self.deck.all())
        if self.rulebook.starter_mission in deck:
            self.deck_draw = [self.starter_mission.id,]
        elif len(deck) == 1:
            self.deck_draw = [deck[0].id,]
        else:
            self.deck_draw = [i.id for i in sample(deck, 2)]
        self.save()


class FlightGroup(models.Model):
    name = models.CharField(max_length=20)
    mission = models.ForeignKey(Mission, on_delete=models.CASCADE, related_name='flight_groups')
    arrival = models.SmallIntegerField(default=1)
    vector = models.CharField(max_length=6)

    ORDERS_CHOICES = (
        ('A', 'Attack'),
        ('S', 'Strike'),
        ('E', 'Escort'),
        ('X', 'Special')
    )
    orders = models.CharField(max_length=1, choices=ORDERS_CHOICES, default="A")

    class Meta:
        verbose_name = 'Flight Group'
        verbose_name_plural = 'Flight Groups'

    def __str__(self):
        return self.name

    def generate(self, pilots, group_init):
        sq = self.squad_members.filter(players__lte=pilots).filter(init__lte=group_init)
        # how many default enemies do we need to replace?
        r = sq.filter(action='R').count()
        squad = []
        for s in sq:
            if r and s.is_default:
                r = r-1
                pass
            else:
                squad.append(s.generate(group_init))
        return squad

    def batch_load(self, setup_list):
        """setup_list should be a list of 6 tuples in (chassis_id, init, action)
           any can be null, we just make some assumptions for those.
           The index of each tuple corresponds to the player count.
        """
        players = 1
        default = (self.mission.enemy_faction.default_ship.id, 1, 'A')
        for s in setup_list:
            if not s: s = default
            action = s[2]
            init = s[1]
            chassis = s[0]
            self.mission.fgsetup_set.create(flight_group=self, chassis_id=chassis, action=action, players=players, init=init)


class FGSetup(models.Model):
    action = models.CharField(max_length=1, choices=( ('A', 'Add'), ('R', 'Replace') ), default='A')
    chassis = models.ForeignKey(Chassis, on_delete=models.CASCADE, null=True, blank=True)
    flight_group = models.ForeignKey(FlightGroup, on_delete=models.CASCADE, related_name='squad_members')
    players = models.SmallIntegerField(default=1)
    init = models.SmallIntegerField(default=1)
    elite = models.BooleanField(default=False)
    enemy = models.ForeignKey(EnemyPilot, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = 'Squad Member'
        verbose_name_plural = 'Squad Members'
        indexes = [
            models.Index(fields=['players']),
            models.Index(fields=['init'])
        ]

    def __str__(self):
        return self.chassis.name if self.chassis else 'Random'

    @cached_property
    def is_default(self):
        return self.chassis == self.flight_group.mission.enemy_faction.default_ship

    def generate(self, group_init):
        from random import choice
        from .sessions import SessionEnemy
        enemies = EnemyPilot.objects.filter(faction=self.mission.enemy_faction)
        if not self.chassis:
            ship = choice(enemies)

            #self.mission.enemy_faction.ships.exclude(id=self.mission.enemy_faction.default_ship.id))
        else:
            ship = self.chassis

        if self.elite:
            e = choice(enemies.filter(chassis=ship.chassis, faction=self.mission.enemy_faction))
            id = e.id
            #abilities = e.ability_list(lvl=group_init)
            abilities = e.abilities.filter(level__lte=group_init)

campaign/models/enemies.py
from django.db import models
from django.utils.functional import cached_property

from xwtools.models import Chassis, Faction, SizeChoice, Card

class EnemyPilot(models.Model):
    chassis = models.ForeignKey(Chassis, on_delete=models.CASCADE)
    faction = models.ForeignKey(Faction, on_delete=models.CASCADE)
    upgrades = models.ManyToManyField(Card, through='EnemyAbility')
    name_override = models.CharField(max_length=35, blank=True, null=True)
    random = models.BooleanField(default=True)

    def __str__(self):
        if self.chassis == self.faction.default_ship:
            return self.chassis.name
        else:
            name = self.name_override or self.in5
            return '{} - {}'.format(self.chassis.name, name)

    def ability_list(self, lvl=1):
        return '/'.join(self.abilities.filter(level__lte=lvl).values_list('card__name', flat=True))

    @cached_property
    def basic(self):
        return '/'.join(self.abilities.filter(level=1).values_list('card__name', flat=True))

    @cached_property
    def elite(self):
        return '/'.join(self.abilities.filter(level=2).values_list('card__name', flat=True))

    @cached_property
    def in3(self):
        return '/'.join(self.abilities.filter(level=3).values_list('card__name', flat=True))

    @cached_property
    def in4(self):
        return '/'.join(self.abilities.filter(level=4).values_list('card__name', flat=True))

    @cached_property
    def in5(self):
        return '/'.join(self.abilities.filter(level=5).values_list('card__name', flat=True))

    @property
    def non_default_ship(self):
        return self.chassis != self.faction.default_ship

    @cached_property
    def large_ship(self):
        return self.chassis.size in (SizeChoice.LARGE, SizeChoice.HUGE)


class EnemyAbility(models.Model):
    pilot = models.ForeignKey(EnemyPilot, on_delete=models.CASCADE, related_name='abilities')
    card = models.ForeignKey(Card, on_delete=models.CASCADE, limit_choices_to={'ai_description__isnull':False})

    class Level(models.IntegerChoices):
        BASIC = 1
        ELITE = 2
        IN_3 = 3
        IN_4 = 4
        IN_5 = 5

    level = models.SmallIntegerField(choices=Level.choices, default=1)

    def __str__(self):
        return self.card.name

campaign/templates/campaign/includes/enemy.html
{% load xwf_extras %}

{% block enemy %}

<div class='container mb-1'>
    <h5>{{enemy.chassis}}</h5>

    <ul class='list-group'>
        {% for ability in enemy.abilities.all %}
        <li class='list-group-item'>{{ability.get_level_display}} - {{ability.card.name}}: {{ability.card.ability}} </li>
        {% endfor %}
    </ul>

</div>

{% endblock enemy %}

campaign/templates/campaign/includes/flight_group.html
{% load xwf_extras %}

{% block fg %}

<div class='row'>
    <div class='col col-1'><strong>{{flight_group}}</strong></div>
    <div class='col col-4'><em>Arrives turn {{flight_group.arrival}}, vector {{flight_group.vector}}</em></div>
</div>
<ul class='row mb-4 list-group'>
    <li class='list-group-item d-inline-flex list-group-item-info'>
        <span class='col-2 flex-fill'>
            <span class='badge badge-secondary'>Init</span>
            Callsign
        </span>
        <span class='col flex-fill'>Ship</span>
    </li>
    {% for ship in ships %}
    <li class='list-group-item d-inline-flex'>
        <span class='col-2 flex-fill'>
            <span class='badge badge-secondary'>{{ship.initiative}}</span>
            {{flight_group}} {{forloop.counter}}
        </span>

        <ul class='col list-group text-left list-group-flush'>
            <li class='list-group-item flex-fill'><a href="{% url 'ai' ship.enemy.chassis.slug %}">{% if ship.elite %}{{'talent'|get_icon}}{% endif %}{{ship}}</a></li>
            {% for a in ship.abilities %}
            <li class='list-group-item'><em>{{a.upgrade.name}}</em>: {{a.upgrade.ai_description}}</li>
            {% endfor %}
        </ul>

    </li>
    {% endfor %}
</ul>

{% endblock fg %}

campaign/templates/campaign/includes/pilot_ship.html
{% load xwf_extras %}

{% block card %}

<div class="card">
    <div class="card-header">
        <h5 class="card-title"><i class="xw-ship xw-ship-{{ship.chassis.css_name}}"></i> {{ship.chassis}}</h5>
        <h6 class="card-subtitle">Initiative {{ship.pilot.initiative}}<h6>
    </div>

    <div class="card-body">
        <div class="row">
            <ul class="list-group mb-3 col-7 float-start">
                <li class="list-group-item attack">{{ship.chassis.get_attack_arc_display|get_icon}}{{ship.chassis.attack}}</li>

                {% if ship.chassis.attack2 %}
                <li class="list-group-item attack">{{ship.chassis.get_attack2_arc_display|get_icon}}{{ship.chassis.attack2}}</li>
                {% endif %}

                <li class="list-group-item agility">{{'agility'|get_icon}}{{ship.chassis.agility}}</li>

                <li class="list-group-item hull">{{'hull'|get_icon|repeat:ship.hull}}</li>

                {% if ship.chassis.shields %}
                <li class="list-group-item shields">{{"shield"|get_icon|repeat:ship.shields}}</li>
                {% endif %}

                {% if ship.pilot.force_charges %}
                <li class="list-group-item force">{{"Force"|get_icon|repeat:ship.pilot.force_charges}}</li>
                {% endif %}
            </ul>

            <ul class="list-group mb-3 col-4 float-end">
                {% for action in ship.chassis.actions.all %}
                <li class="list-group-item">
                    <span class="{{action.difficulty_css}}">{{action.get_action_display|get_icon}}</span>
                    {% if action.linked_action %} {{'linked'|get_icon}}
                    <span class="{{action.linked_difficulty_css}}">{{action.get_linked_action_display|get_icon}}</span>
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
        </div>

        <div class="row mb-3">
            {% if ship.chassis.ability %}
            <span><strong>{{ship.chassis.ability}}</strong>: {{ship.chassis.ability.description|iconize}}</span>
            {% endif %}
        </div>
    </div>



    <div class="card-footer">
        {% if slots %}
        <ul class="col list-group list-group-horizontal">
            {% for slot in slots %}
            <li class="list-group-item">{{slot.label|get_icon}}<li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>

{% endblock card %}

campaign/templates/campaign/includes/upgrade_card.html
{% load xwf_extras %}

{% block card %}

<div class='upgrade-card card g-0 me-2 mb-2'>
    <a card_id={{upgrade.id}} href='#'
        class="card-header text-decoration-none
        {% if status == 'X' %} bg-danger text-light
        {% elif status == 'E' %} bg-success text-light
        {% endif %}"
        <h5 class='card-title'>
            {{upgrade.get_type_display|get_icon}}
            {% if upgrade.type2 %}
            {{upgrade.get_type2_display|get_icon}}
            {% endif %}
            {{upgrade}}
        </h5>
        <span class="float-end">
            <i class="xwing-miniatures-font xwing-miniatures-font-squad-point-cost"></i>
            {{cost}}
            {% if upgrade.name in pilot.campaign.limited_upgrades %}
            {{'token-stress-outline'|get_icon}}
            {% endif %}
        </span>
    </a>

  <div class='card-body'>
      <p>{{upgrade.description|iconize}}</p>
      {% if upgrade.requires %}
      <p>Requires: {{upgrade.requires|iconize}}</p>
      {% endif %}
  </div>

  <div class="card-footer">
      <ul class='list-group list-group-horizontal'>
          {% if upgrade.attack %}
          <li class="list-group-item attack">
              <span>{{upgrade.attack.get_arc_display|get_icon}}{{upgrade.attack.dice}}
                  {% if upgrade.attack.ordnance %}{{"Ordnance"|get_icon}}{% endif %}
                  {{upgrade.attack.range}}
              </span>
          </li>
          {% endif %}

          {% if upgrade.adds %}
          <li class='list-group-item'>
              <span>
                  {{upgrade.adds|iconize}}
              </span>
          </li>
          {% endif %}

          {% if upgrade.charges %}
          <li class='list-group-item'>
              <span>
                  {% if upgrade.force %}{{"Force#force"|get_icon|repeat:upgrade.charges}}
                  {% else %}{{"Charge#charge"|get_icon|repeat:upgrade.charges}}
                            {% if upgrade.recurring %}{{'recurring'|get_icon}}{% endif %}
                  {% endif %}
              </span>
          </li>
          {% endif %}
      </ul>
      </div>
</div>

{% endblock card %}