campaign/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

app_name = 'game'

router = DefaultRouter()
router.register(r'user', views.UserViewSet)
router.register(r'pilot', views.PilotViewSet)

urlpatterns = [
    path('pilot/<int:pk>', views.PilotUpdate.as_view(), name='pilot'),
    path('rulebook/<int:pk>', views.RulebookView.as_view(), name='rulebook'),

    path('campaign/<int:pk>', views.CampaignView.as_view(), name='campaign'),
    #path('campaign/<int:pk>/plan', views.CampaignUpdate.as_view(), name='campaign-plan'),

    path('campaign/<int:pk>/plan', views.SessionPlan.as_view(), name='next-mission'),

    path('session/<int:session_id>', views.session_summary, name='session'),
    path('session/<int:pk>/debrief', views.SessionDebrief.as_view(), name='session-debrief'),

    path('profile/', views.player_page, name='player_profile'),
    path('player/<int:player_id>', views.player_page, name="player_update"),

    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

campaign/models/ai.py
from django.db import models
from django.utils.functional import cached_property

from .campaigns import Rulebook
from xwtools.models import Dial, DialManeuver, ArcDirectionChoice, RangeChoice


class AI(models.Model):
    rulebook = models.ForeignKey(Rulebook, on_delete=models.CASCADE)
    dial = models.ForeignKey(Dial, on_delete=models.CASCADE)
    flee = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return '{} AI'.format(self.dial.chassis.name)


    def mirror(self):
        """
        A helper function that makes left-sided copies of all the right-side maneuver tables
        :return: Nothing, saves new objects directly
        """
        right_arcs = (ArcDirectionChoice.FR, ArcDirectionChoice.RF, ArcDirectionChoice.RA, ArcDirectionChoice.AR)

        for mv in self.aimaneuver_set.filter(arc__in=right_arcs):
            new_arc = mv.arc.replace('R', 'L')
            if not self.aimaneuver_set.filter(arc=new_arc, range=mv.range).exists():
                mv.pk = None
                mv.arc = new_arc
                mv.roll_1 = mv.roll_1.find_mirror()
                mv.roll_2 = mv.roll_2.find_mirror()
                mv.roll_3 = mv.roll_3.find_mirror()
                mv.roll_4 = mv.roll_4.find_mirror()
                mv.roll_5 = mv.roll_5.find_mirror()
                mv.roll_6 = mv.roll_6.find_mirror()
                mv.save()

    class Meta:
        verbose_name_plural = 'AI'

    @cached_property
    def has_special(self):
        return self.aimaneuver_set.filter(arc=ArcDirectionChoice.SP).exists()


class AIManeuver(models.Model):
    ai = models.ForeignKey(AI, on_delete=models.CASCADE)
    arc = models.CharField(max_length=2, choices=ArcDirectionChoice.choices)
    range = models.CharField(max_length=1, choices=RangeChoice.choices)

    # these are denormalized mainly to make data entry easier, so we don't need
    # to have an AI, AIManeuver, and a theoretical AIManeuverRoll model all on one admin page
    roll_1 = models.ForeignKey(DialManeuver, on_delete=models.CASCADE, related_name='roll_1')
    roll_2 = models.ForeignKey(DialManeuver, on_delete=models.CASCADE, related_name='roll_2')
    roll_3 = models.ForeignKey(DialManeuver, on_delete=models.CASCADE, related_name='roll_3')
    roll_4 = models.ForeignKey(DialManeuver, on_delete=models.CASCADE, related_name='roll_4')
    roll_5 = models.ForeignKey(DialManeuver, on_delete=models.CASCADE, related_name='roll_5')
    roll_6 = models.ForeignKey(DialManeuver, on_delete=models.CASCADE, related_name='roll_6')

    class Meta:
        ordering = ['arc', 'range']

    def get_maneuvers(self): return True

    @cached_property
    def rolls(self):
        return [self.roll_1, self.roll_2, self.roll_3, self.roll_4, self.roll_5, self.roll_6]

    @cached_property
    def arc_order(self):
        return ['FL', 'BE', 'FR', 'LF', 'RF', 'LA', 'RA', 'AL', 'AR'].index(self.arc)


class AIPriority(models.Model):
    TYPE_CHOICES = (
        ('U', 'System Phase'),
        ('T', 'Target'),
        ('A', 'Action')
    )
    ai = models.ForeignKey(AI, on_delete=models.CASCADE, related_name='priorities')
    type = models.CharField(max_length=1, choices=TYPE_CHOICES)
    step = models.PositiveSmallIntegerField(default=1)
    desc = models.CharField(max_length=75)

    class Meta:
        verbose_name_plural = 'AI Priorities'
        ordering = ['-type', 'step']

campaign/models/campaigns.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.utils.functional import cached_property

from math import floor

from xwtools.models import Chassis, Faction, SlotChoice, Card
from .enemies import EnemyPilot


class User(AbstractUser):
    pass


class UpgradeLogic(models.IntegerChoices):
    HOTAC = 1, 'HotAC'
    TEST = 2, 'Test'


class FeatureChoice(models.TextChoices):
    EMPLACEMENT = 'E', 'Emplacement'
    OBSTACLE = 'O', 'Obstacle'
    TERRAIN = 'T', 'Terrain'


class Rulebook(models.Model):
    description = models.CharField(max_length=30)
    admin = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    faction = models.ForeignKey(Faction, on_delete=models.SET_NULL, null=True)
    ships = models.ManyToManyField(Chassis, through='PlayableShip')

    # player defaults
    start_init = models.PositiveSmallIntegerField(default=2)

    # configure a campaign's XP costs
    ship_cost = models.PositiveSmallIntegerField(default=5)

    upgrade_logic = models.PositiveSmallIntegerField(choices=UpgradeLogic.choices)
    initiative_progression = models.PositiveSmallIntegerField(choices=UpgradeLogic.choices)
    initiative_cost = models.PositiveSmallIntegerField(default=3)

    starter_mission = models.ForeignKey('Mission', on_delete=models.SET_NULL, null=True, related_name='starts')

    def __str__(self):
        return self.description

    def get_absolute_url(self):
        return reverse('ruleset', kwargs={'pk': self.pk})

    def get_initiative_cost(self, initiative):
        """
        Returns the XP cost of advancing to from 'iniative'-1 to 'initiative'.
        """
        if self.initiative_progression == UpgradeLogic.TEST:
            return (initiative*self.initiative_cost)^2
        elif self.initiative_progression == UpgradeLogic.HOTAC:
            return initiative * self.initiative_cost
        else:
            return 0


class PlayableShip(models.Model):
    rulebook = models.ForeignKey(Rulebook, on_delete=models.CASCADE)
    chassis = models.ForeignKey(Chassis, on_delete=models.CASCADE)
    xp_value = models.SmallIntegerField(default = 0)

    PROGRESSION_TYPES = (
        ('d', 'Default'),
        ('h', 'HWK-290')
    )
    progression = models.CharField(max_length=1, choices=PROGRESSION_TYPES, default='d')

    @cached_property
    def name(self):
        return self.chassis.name

    def __str__(self):
        return self.name


class MissionFeature(models.Model):
    name = models.CharField(max_length=30)
    type = models.CharField(max_length=1, choices=FeatureChoice.choices)
    setup_code = models.CharField(max_length=1, blank=True)
    attack = models.PositiveSmallIntegerField(null=True, blank=True)
    attack_range = models.CharField(max_length=3, blank=True)
    hull = models.PositiveSmallIntegerField(null=True, blank=True)
    shields = models.PositiveSmallIntegerField(null=True, blank=True)
    agility = models.PositiveSmallIntegerField(null=True, blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    @cached_property
    def is_emplacement(self):
        return self.type == FeatureChoice.EMPLACEMENT

class Mission(models.Model):
    FRIENDLY = 'F'
    NEUTRAL = 'N'
    HOSTILE = 'H'
    TERRITORY_CHOICES = (
        (FRIENDLY, 'Friendly'),
        (NEUTRAL, 'Neutral'),
        (HOSTILE, 'Hostile')
    )
    name = models.CharField(max_length=30)
    story = models.CharField(max_length=30)
    sequence = models.PositiveSmallIntegerField()
    enemy_faction = models.ForeignKey(Faction, on_delete=models.CASCADE, default=1)
    territory = models.CharField(max_length=1, choices=TERRITORY_CHOICES, default=NEUTRAL)
    rulebook = models.ForeignKey(Rulebook, on_delete=models.SET_NULL, null=True)
    turns = models.PositiveSmallIntegerField(default=12)

    player_vp = models.BooleanField(default=False)
    enemy_vp =  models.BooleanField(default=False)

    objective = models.TextField()
    bonus_1 = models.TextField(blank=True, null=True)
    bonus_2 = models.TextField(blank=True, null=True)
    penalty = models.TextField(blank=True, null=True)

    ground_assault = models.BooleanField(default=False)

    features = models.ManyToManyField(MissionFeature, blank=True)

    class Meta:
        ordering = ['story', 'sequence']
        indexes = [
            models.Index(fields=['story', 'sequence']),
            models.Index(fields=['rulebook']),
            models.Index(fields=['player_vp'])
        ]

    def __str__(self):
        return '{} ({} {})'.format(self.name, self.story, self.sequence)


class Campaign(models.Model):
    rulebook = models.ForeignKey(Rulebook, on_delete=models.SET_NULL, null=True)
    gm = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='campaign_gm')
    players = models.ManyToManyField(User)
    description = models.CharField(max_length=30)

    victory = models.PositiveSmallIntegerField(default=12)
    pool_xp = models.BooleanField(default=False)

    deck = models.ManyToManyField(Mission)
    deck_draw = models.JSONField(null=True)

    exclude_random = models.ManyToManyField(Chassis, blank=True)

    def __str__(self):
        return self.description

    @property
    def victory_points(self):
        return self.session_set.filter(outcome='V', player_vp=True).Count()

    @cached_property
    def xp_share(self):
        """
        Used when XP pooling is chosen for the game.
        Calculates total xp across all sessions and total number of pilot shares.
        Each mission flown earns a pilot one share in the group's total xp.
        """
        pilots = 0
        xp = 0
        for s in self.session_set.all():
            pilots = pilots + s.pilots.count()
            xp = xp + s.xp_total
        return floor(xp/pilots)

    @cached_property
    def limited_upgrades(self):
        from .pilots import PilotUpgrade
        return PilotUpgrade.objects.filter(pilot__campaign=self, card__limited=True).values_list('card__name', flat=True)

    def starting_deck(self):
        for m in Mission.objects.filter(rulebook=self.rulebook, sequence=1):
            self.deck.add(m)
        self.save()

    def draw_missions(self):
        from random import sample
        deck = list(self.deck.all())
        if self.rulebook.starter_mission in deck:
            self.deck_draw = [self.starter_mission.id,]
        elif len(deck) == 1:
            self.deck_draw = [deck[0].id,]
        else:
            self.deck_draw = [i.id for i in sample(deck, 2)]
        self.save()


class FlightGroup(models.Model):
    name = models.CharField(max_length=20)
    mission = models.ForeignKey(Mission, on_delete=models.CASCADE, related_name='flight_groups')
    arrival = models.SmallIntegerField(default=1)
    vector = models.CharField(max_length=6)

    ORDERS_CHOICES = (
        ('A', 'Attack'),
        ('S', 'Strike'),
        ('E', 'Escort'),
        ('X', 'Special')
    )
    orders = models.CharField(max_length=1, choices=ORDERS_CHOICES, default="A")

    class Meta:
        verbose_name = 'Flight Group'
        verbose_name_plural = 'Flight Groups'

    def __str__(self):
        return self.name

    def generate(self, pilots, group_init):
        sq = self.squad_members.filter(players__lte=pilots).filter(init__lte=group_init)
        # how many default enemies do we need to replace?
        r = sq.filter(action='R').count()
        squad = []
        for s in sq:
            if r and s.is_default:
                r = r-1
                pass
            else:
                squad.append(s.generate(group_init))
        return squad

    def batch_load(self, setup_list):
        """setup_list should be a list of 6 tuples in (chassis_id, init, action)
           any can be null, we just make some assumptions for those.
           The index of each tuple corresponds to the player count.
        """
        players = 1
        default = (self.mission.enemy_faction.default_ship.id, 1, 'A')
        for s in setup_list:
            if not s: s = default
            action = s[2]
            init = s[1]
            chassis = s[0]
            self.mission.fgsetup_set.create(flight_group=self, chassis_id=chassis, action=action, players=players, init=init)


class FGSetup(models.Model):
    action = models.CharField(max_length=1, choices=( ('A', 'Add'), ('R', 'Replace') ), default='A')
    chassis = models.ForeignKey(Chassis, on_delete=models.CASCADE, null=True, blank=True)
    flight_group = models.ForeignKey(FlightGroup, on_delete=models.CASCADE, related_name='squad_members')
    players = models.SmallIntegerField(default=1)
    init = models.SmallIntegerField(default=1)
    elite = models.BooleanField(default=False)
    enemy = models.ForeignKey(EnemyPilot, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        verbose_name = 'Squad Member'
        verbose_name_plural = 'Squad Members'
        indexes = [
            models.Index(fields=['players']),
            models.Index(fields=['init'])
        ]

    def __str__(self):
        return self.chassis.name if self.chassis else 'Random'

    @cached_property
    def is_default(self):
        return self.chassis == self.flight_group.mission.enemy_faction.default_ship

    def generate(self, group_init):
        from random import choice
        from .sessions import SessionEnemy
        enemies = EnemyPilot.objects.filter(faction=self.mission.enemy_faction)
        if not self.chassis:
            ship = choice(enemies)

            #self.mission.enemy_faction.ships.exclude(id=self.mission.enemy_faction.default_ship.id))
        else:
            ship = self.chassis

        if self.elite:
            e = choice(enemies.filter(chassis=ship.chassis, faction=self.mission.enemy_faction))
            id = e.id
            #abilities = e.ability_list(lvl=group_init)
            abilities = e.abilities.filter(level__lte=group_init)

campaign/templates/campaign/campaign.html
{% extends 'base.html' %}

{% block content %}

<div class="row mb-3">
    <div class="col">
        <h2>{{campaign.description}}</h2>
    </div>
</div>

<div class="row">
    <div class="col">
        <a href="{% url 'game:next-mission' campaign.id %}">Next Mission</a>
    </div>
</div>

<div class="row mb-3">
    <div class="col">
        <h3>Sessions</h3>
        <div class="list-group">
            {% for session in campaign.session_set.all %}
            <a href="{% url 'game:session' session.id %}" class="list-group-item list-group-item-action">{{session.mission}}</a>
            {% if session.outcome == 'U' %}<a href="{% url 'game:session-debrief' session.id %}">Debrief</a>{% endif %}
            {% endfor %}
        </div>
    </div>
</div>


<div class="row mb-3">
    <div class="col">
        <h3>Pilots</h3>
        <div class="list-group">
            {% for pilot in campaign.pilots.all %}
            <a href="{% url 'game:pilot' pilot.id %}" class="list-group-item list-group-item-action">{{pilot.callsign}}</a>
            {% endfor %}
        </div>
    </div>
</div>

<div class="row mb-3">
  <div class="col">
    <h3>Available Ships</h3>
    <div class="list-group">
    {% for ship in campaign.rulebook.ships.all %}
      <a href="{% url 'chassis' chassis_slug=ship.slug %}" class="list-group-item list-group-item-action">{{ship.name}}</a>
    {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

campaign/templates/campaign/chassis.html
{% extends 'base.html' %}

{% load xwf_extras %}

{% block content %}
        <div class="row mb-2">
                <div class="col-3">
                    <h5><i class="xw-ship xw-ship-{{ship.css_name}}"></i> {{ship.name}}</h5>
                </div>
        </div>

        <div class="row mb-2">
                <div class="col-3">
                    <h5>Base XP: {{ship.start_xp}}</h5>
                </div>
        </div>

        <div class="row">
            <div class="col">
                <h6>Upgrade Slots</h6>
                <ul class="list-group list-group-horizontal">
                {% for slot in ship.slots.all %}
                  <li class="list-group-item">{{slot.get_type_display|get_icon}}<li>
                {% endfor %}
                </ul>
            </div>
        </div>

    <!-- dial -->
    {% regroup ship.dial.maneuvers.all by speed as speed_rows %}
    <div class="row col-6">
    {% for spd, mvs in speed_rows %}
        <div class="col-1"><em>{{spd}}</em></div>
        {% for cell in mvs|dial_pad:ship.dial.dial_width %}
        <div class="col-1"></div>
        {% endfor %}
        {% for mv in mvs %}
        <div class="col-1 {{mv.icon_color}}">{{mv.css_name|get_icon}}</div>
        {% endfor %}
        <div class="w-100"></div>
    {% endfor %}
    </div>


{% endblock %}

campaign/templates/campaign/enemy_list.html
{% extends 'base.html' %}

{% load xwf_extras %}

{% block content %}

{% for enemy in enemy_list %}
    {% block enemy %}
    {% include './includes/enemy.html' %}

    {% endblock enemy %}
{% endfor %}

{% endblock content %}

campaign/templates/campaign/enemy_pilot.html
{% extends 'base.html' %}

{% load xwf_extras %}

{% block content %}

    {% block enemy %}
    {% include './includes/enemy.html' %}

    {% endblock enemy %}

{% endblock content %}

campaign/templates/campaign/index.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}
<h4>Your Games</h4>
{% for game in campaigns %}
    <div class='card mb-3'>
        <div class='card-body'>
            <h5 class="card-title"><a href="{% url 'game:campaign' game.id %}">{{game.description}}</a></h5>
            <h6 class="card-subtitle">{{game.rulebook}}</h6>
            <table class='table table-sm'>
                <tr>
                    <th scope='col'>Pilot</th>
                    <th scope='col'>Ship</th>
                    <th scope='col'>Player</th>
                </tr>
                {% for p in game.pilots.all %}
                <tr>
                    <td scope='col'><a href='{% url 'game:pilot' p.id %}'>{{p.callsign}}</a></td>
                    <td scope='col'>{{p.active_ship}}</td>
                    <td scope='col'>{{p.user}}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endfor %}
{% endif %}

{% endblock %}

campaign/templates/campaign/pilot.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load xwf_extras %}
{% load static %}

{% block title %}{{pilot}}{% endblock %}

{% block content %}

<h3>{{pilot.callsign}}{% if pilot.user.username != pilot.callsign %} ({{pilot.user}}){% endif %}</h3>
<h5>Campaign: <a href="{% url 'game:campaign' pilot.campaign.id %}">{{pilot.campaign}}</a></h5>

<div class='row mb-3' id='pilot-stats'>
    <div class='col-sm-5'>
        {% include './includes/pilot_ship.html' with ship=pilot.active_ship slots=pilot.slots %}
    </div>
</div>

<div class="row mb-3">
    <ul class="nav nav-tabs" id="sheet-nav" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="upgrade-tab" data-bs-toggle="tab"
                  data-bs-target="#upgrades" type="button" role="tab"
                  aria-controls="upgrades" aria-selected="true">Upgrades</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="purchase-tab" data-bs-toggle="tab"
                  data-bs-target="#purchase" type="button" role="tab"
                  aria-controls="purchase" aria-selected="false">Purchase</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="stats-tab" data-bs-toggle="tab"
                  data-bs-target="#stats" type="button" role="tab"
                  aria-controls="stats" aria-selected="false">Statistics</button>
        </li>
    </ul>
</div>

<div class="row mb-3 tab-content d-flex flex-wrap">
    <div class="tab-pane active" role="tabpanel" aria-labelledby="upgrade-tab" id="upgrades">
        <div class="container">
            <div class="row mb-5 d-flex flex-wrap ">
            {% for gu in pilot.upgrades.all %}
            {% ifchanged gu.card.type %}
            </div>
            <div class="row mb-5 d-flex flex-wrap">
            {% endifchanged %}
            {% include './includes/upgrade_card.html' with upgrade=gu.card cost=gu.cost status=gu.status %}
            {% endfor %}
            </div>
        </div>
    </div>

    <div class="tab-pane" role="tabpanel" aria-labelledby="purchase-tab" id="purchase">
        <div class="container">
            <div class="row mb-3">
                <form method="POST">
                {% crispy form  %}
                 {{ update.management_form }}
                {% crispy update  %}
                <p><i class="xwing-miniatures-font xwing-miniatures-font-squad-point-cost"></i>{{remaining}} available</p>
                <p>Next Initiative:
                    {% if init_upgrade_cost %}<i class="xwing-miniatures-font xwing-miniatures-font-squad-point-cost"></i>{{init_upgrade_cost}}
                    {% else %}Maxed Out
                    {% endif %}<p>
                </form>
            </div>

            {% regroup pilot.available_upgrades.all by get_type_display as upgrades %}
            <nav id="available-nav" class="row navbar navbar-light">
                <ul class="nav nav-pills">
                     {% for type in upgrades %}
                     <li class="nav-item">
                         <a href="#available-list-{{type.grouper}}" class="nav-link">{{type.grouper|get_icon}}</a>
                     </li>
                     {% endfor %}
                 </ul>
            </nav>

            <div id="available-list" class="row scrollspy border pt-2 rounded"
                 data-bs-spy="scroll" data-bs-target="#available-nav" data-bs-offset="0">
            {% for type in upgrades %}
                <div id="available-list-{{type.grouper}}" class="row mb-5 d-flex flex-wrap">
                    {% for upgrade in type.list %}
                    {% include './includes/upgrade_card.html' with cost=upgrade|get_cost:pilot.campaign.rulebook.upgrade_logic %}
                    {% endfor %}
                </div>
            {% endfor %}
            </div>

            <div class="row mb-5 d-flex flex-wrap">
            </div>
        </div>
    </div>

    <div class="tab-pane" role="tabpanel" aria-labelledby="stats-tab" id="stats">
        <div class="container">
            <div class="row mb-3 d-flex flex-wrap">
                <div class="col-sm-4">
                    <p>Missions Flown: {{pilot.sessions.count}}</p>
                    <p>XP Earned: <i class="xwing-miniatures-font xwing-miniatures-font-squad-point-cost"></i>{{pilot.total_xp}}</p>

                    <p>XP Spent: <i class="xwing-miniatures-font xwing-miniatures-font-squad-point-cost"></i>{{pilot.spent_ships}} Ships,
                               <i class="xwing-miniatures-font xwing-miniatures-font-squad-point-cost"></i>{{pilot.spent_initiative}} Initiative,
                               <i class="xwing-miniatures-font xwing-miniatures-font-squad-point-cost"></i>{{pilot.spent_upgrades}} Upgrades
                           </p>
                    <p>XP Available: <i class="xwing-miniatures-font xwing-miniatures-font-squad-point-cost"></i>{{remaining}}</p>
                </div>
                <ul class="list-group list-group-flush col-sm-3">
                    <li class="list-group-item">Kills</li>
                    {% for kill in pilot.kills %}
                    <li class="list-group-item">{{kill.css_name|ship_icon|repeat:kill.id__count}}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>


{% endblock content %}

{% block extrajs %}
    <script src="{% static 'js/pilot_upgrade.js' %}"></script>
{% endblock extrajs %}

campaign/templates/campaign/player.html
{% extends 'base.html' %}

{% load xwf_extras %}

{% block content %}

<h3>{{player.username}}</h3>
<h6>{{player.first_name}} {{player.last_name}}</h6>
<p><a href="{% url 'admin:password_change' %}">Change Password</a/</p>

{% regroup player.pilot_set.all by campaign as campaign_list %}
    {% for campaign in campaign_list %}
    <div class="card mb-3">
        <div class="card-header">
            <a href="{% url 'game:campaign' campaign.grouper.id %}">{{campaign.grouper}}</a>
        </div>
        <div class="list-group list-group-flush">
            {% for pilot in campaign.list %}
            <a href="{% url 'game:pilot' pilot.id %}" class="list-group-item list-group-item-action">{{pilot.callsign}}</a>
            {% endfor %}
        </div>
    </div>
    {% endfor %}

{% endblock content %}

campaign/templates/campaign/s2.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <h4 class='mb-2'>{{session.mission}}</h4>

    <nav id='menu-panel' class='nav nav-tabs mb-4' role='tablist'>
        <a id='mission-tab' class='nav-link' data-toggle="tab" role="tab" aria-controls="home" aria-selected="true" href='#mission'>Mission</a>
        <a id='achievement-tab' class='nav-link' data-toggle='tab' role="tab" aria-controls="home" aria-selected="true" href='#achievements'>Achievements</a>
        <a id='pilot-tab' class='nav-link' data-toggle="tab" role="tab" aria-controls="home" aria-selected="true" href='#pilots'>Pilots</a>
        <a id=enemy-tab' class='nav-link' data-toggle="tab" role="tab" aria-controls="home" aria-selected="true" href='#enemies'>Enemies</a>
    </nav>

    <div class='tab-content'>
        <div id='mission' class='tab-pane active' role="tabpanel" aria-labelledby="mission-tab">
            <p>{{session.mission}}</p>
            <p>{{session.mission.get_territory_display}} Territory</p>
            <p>{{session.date}}</p>
            <p>Outcome: {{session.get_outcome_display}}</p>
        </div>

        <div id='achievements' class='tab-pane active' role="tabpanel" aria-labelledby="achievement-tab">
            <ul class='list-group'>
                <li class='list-group-item'><span class='col'>Turn</span><span class='col'>Pilot</span><span class='col'>Event</span><span class='col'>Target</span></li>
                {% for ach in session.achievements.all %}
                <li class='list-group-item'><span class='col'>{{ach.turn}}</span>
                                            <span class='col'>{{ach.pilot}}</span>
                                            <span class='col'>{{ach.event}}</span>
                                            <span class='col'>{{ach.target}}</span>
                </li>
                {% endfor %}
                {% crispy formset helper %}
        </div>


        <div id='pilots' class='tab-pane' role="tabpanel" aria-labelledby="pilot-tab">
            {% for p in session.pilots.all %}
            <p>{{p.callsign}}</p>
            {% endfor %}

            <ul class='list-group'>
                {% for a in achievements %}
                <li class='list-group-item'><strong>{{a.pilot__callsign}}</strong> {{a.event__short_desc}} x{{a.total}} ({{a.xp}} XP)</li>
                {% endfor %}
            </ul>

        </div>

        <div id='enemies' class='tab-pane' role="tabpanel" aria-labelledby="enemy-tab">
            <ul class='list-group'>
                {% regroup session.sessionenemy_set.all by flight_group as flight_groups %}
                {% for flight_group, ships in flight_groups %}
                    {% block fg %}
                    {% include './includes/flight_group.html' %}
                    {% endblock fg %}
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}