campaign/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

app_name = 'game'

router = DefaultRouter()
router.register(r'user', views.UserViewSet)
router.register(r'pilot', views.PilotViewSet)

urlpatterns = [
    path('pilot/<int:pk>', views.PilotUpdate.as_view(), name='pilot'),
    path('rulebook/<int:pk>', views.RulebookView.as_view(), name='rulebook'),

    path('campaign/<int:pk>', views.CampaignView.as_view(), name='campaign'),
    #path('campaign/<int:pk>/plan', views.CampaignUpdate.as_view(), name='campaign-plan'),

    path('campaign/<int:pk>/plan', views.SessionPlan.as_view(), name='next-mission'),

    path('session/<int:session_id>', views.session_summary, name='session'),
    path('session/<int:pk>/debrief', views.SessionDebrief.as_view(), name='session-debrief'),

    path('profile/', views.player_page, name='player_profile'),
    path('player/<int:player_id>', views.player_page, name="player_update"),

    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

campaign/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        {% block stylesheet %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
              rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
              crossorigin="anonymous">
        <link rel="stylesheet" type="text/css"  href="{% static 'xwf/xwing-miniatures.css' %}">
            <link rel="stylesheet" type="text/css" href="{% static 'hotac/style.css' %}">
        {% endblock %}
    </head>

    <body>
        <header class="d-flex flex-wrap align-items-center justify-content-center
                       justify-content-md-between py-3 mb-4 border-bottom
                       bg-dark text-white">
          <ul class="nav col-12 col-md-auto justify-content-center">
            <li><a class="nav-link text-white text-decoration-none px-2" href="{% url 'index' %}">HotAC Manager</a></li>
            <li><a class="nav-link text-white text-decoration-none px-2" href='#'>AIs</a></li>
          </ul>
          <div class="col-md-3 text-end">
            {% if user.is_authenticated %}
            <a href="{% url 'game:player_profile' %}" class="btn btn-outline-light" type="button">{{user.username}}</button>
            <a href="{% url 'logout' %}" class="btn btn-outline-warning">Log Out</a>
            {% else %}
            <a href="{% url 'login' %}" class="btn btn-outline-light">Log In</a>
            {% endif %}
          </div>
        </header>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>

        {% block js %}
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
                    crossorigin="anonymous">
            </script>

            <script src="https://code.jquery.com/jquery-3.6.0.min.js"
                    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
                    crossorigin="anonymous">
            </script>
            {# htmx 1.7.0 #}
            <script src="{% static 'js/htmx.min.js' %}"></script>
        {% endblock %}

        {% block extrajs %}
        {% endblock %}
    </body>
</html>